#!/usr/bin/env ruby

f = rand(1..3);
sleep(0.05);

s = rand(1..10) if f == 1; sleep(0.05);
s = rand(1..5) if f == 2; sleep(0.05);
s = rand(1..2) if f == 3; sleep(0.05);

if f == 1 and (s > 1 and s < 8)
    e = rand(1..22);
    sleep(0.05);
else
    e = rand(1..20);
    sleep(0.05);
end

puts "Stargate SG1, Season #{s}, Episode #{e}" if f == 1;
puts "Stargate Atlantis, Season #{s}, Episode #{e}" if f == 2;
puts "Stargate Universe, Season #{s}, Episode #{e}" if f == 3;
