#!/bin/sh

chmod 755 update
chmod 755 random
chmod 755 turnin

./update

apt-get install git -y
apt-get install vim -y
#git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
#sh ~/.vim_runtime/install_awesome_vimrc.sh
#dircolors -p | sed 's/;42/;01/' > ~/.dircolors
#source ~/.bashrc
ln -s /mnt/c/Users/roott/Documents/C++/ C++
cd C++
./wsl_setup
cd ..

cp ./* ../
cp ./.* ../

./update
