#!/bin/sh



########## CUSTOMIZE ############
#################################
user_name="cse74147"
inner_client="opti3060ws06"
#################################
#################################



class=$1
filename=$2

#if [ ! -f "./.ssh/id_rsa" ]
#then
#    echo "Setting up SSH settings"
#    echo "Once setup, connecting to the ssh server will not require a password"
#    sleep 3
######    HOSTNAME=`hostname` ssh-keygen -t rsa -C "$HOSTNAME" -f "$HOME/.ssh/id_rsa" -P "" && cat ~/.ssh/id_rsa.pub
#    clear;
######    cat .ssh/id_rsa.pub | ssh $user_name@scylla.cs.uoi.gr 'cat >>.ssh/authorized_keys'

#    ssh -tt $user_name@scylla.cs.uoi.gr << EOF
#        HOSTNAME=`hostname` && ssh-keygen -t rsa -C "$HOSTNAME" -f "/usr/home/students/stud17/cse74147/id_rsa" -P "" && cat /usr/home/students/stud17/cse74147/id_rsa.pub
#        cp id_rsa* .ssh/
#        cat id_rsa.pub | ssh $inner_client 'cat >>.ssh/authorized_keys'
#        exit
#EOF
#fi

if [ -d $filename ]; then
    ssh $user_name@scylla.cs.uoi.gr "mkdir Documents/$(basename -- $filename)"

    sftp $user_name@scylla.cs.uoi.gr << EOF
mput $filename/* Documents/$(basename -- $filename)/
quit
EOF

    ssh $user_name@scylla.cs.uoi.gr "ssh $inner_client turnin $class Documents/$(basename -- $filename)/*; rm -r Documents/*"
else
    if [ -f $filename ]; then
        sftp $user_name@scylla.cs.uoi.gr << EOF2
put $filename Documents/
quit
EOF2
        ssh $user_name@scylla.cs.uoi.gr "ssh $inner_client turnin $class Documents/$(basename -- $filename); rm -r Documents/*"
    fi
fi

